<a href="https://colab.research.google.com/github/samreenkauser/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/practice_python_collection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
sys.version

'3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]'

python# New Section

Pythin Comment

In [3]:
print("Hello")

Hello


mutiple comment

In [4]:
num = 5
square = num * num
print(square)

25


UNIT 2

In [5]:
_abc = "hello"
print(_abc)

hello


In [6]:
x = 3
print(x)
print (type(x))

3
<class 'int'>


In [7]:
y = 6.5
print(y)
print(type(y))

6.5
<class 'float'>


In [8]:
t = "olaf"
print(t)
print(type(t))

olaf
<class 'str'>


In [9]:
u = 5+3j
print(u)
print(type(u))

(5+3j)
<class 'complex'>


In [10]:
x = (2,3,4)
print(x)
print(type(x))

(2, 3, 4)
<class 'tuple'>


In [11]:
x= [23,24,24]
print(x)
print(type(x))

[23, 24, 24]
<class 'list'>


In [12]:
x = {23,42,54}
print(x)
print(type(x))

{42, 54, 23}
<class 'set'>


In [13]:
x = {'a': 20, 'b': 40}
print(x)
print(type(x))

{'a': 20, 'b': 40}
<class 'dict'>


Operator in python

In [14]:
a = 4
b = 5
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)

9
-1
20
0.8
4


In [15]:
a = 5
print(a**86)

1292469707114105741986576081359316958696581423282623291015625


UNIT - 3 BUILT IN FUNCTIONS

In [16]:
x = 10
y = 5
expression = "x*y*3*4/6+45-45*45+64"
result = eval(expression)
print(result)

-1816.0


In [17]:
a = -10
print(abs(a))

10


In [18]:
ert = [1,2,3,4,5,6,7,53,56,346,54,64,33335,5643,34]
total = sum(ert)
print(total)

39613


In [19]:
result = pow(345.24,5)
print(result)

4904621975482.74


In [20]:
a = input("enter your age")
print(a)
print(type(a))

enter your age21
21
<class 'str'>


In [21]:
a = input("enter your age")
print(type(a))
b = int(a)
print(b)
print(type(b))

enter your age21
<class 'str'>
21
<class 'int'>


In [58]:
abc = 53
print(abc)
print(type(abc))
xyz = str(abc)
print(xyz)
print(type(xyz))

53
<class 'int'>
53
<class 'str'>


In [59]:
a = input("enter price")
print(type(a))
b = float(a)
print(b)
print(type(b))

enter price500
<class 'str'>
500.0
<class 'float'>


In [60]:
a = "Hello i am a wonderer"
print(len(a))

21


In [61]:
num1 = float(input("Enter the first number:"))
num2 = float(input("Enter the second number:"))
sum = num1 +num2
print("The sum of", num1,"and",num2,"is:", sum)

Enter the first number:1
Enter the second number:2
The sum of 1.0 and 2.0 is: 3.0


UNIT - 4

In [62]:
i = 20

if(i>10):
  print("10 is less than 20")
  print("I am outside the if block")

10 is less than 20
I am outside the if block


In [63]:
age = int(input("Enter age"))
if age>18:
  print("you can vote")
else:
    print("you can't vote")

Enter age21
you can vote


In [64]:

# Write a python program that prompts the user to input a city and displays thee faomus monument of that city.
# Mumbai: Gateway of India
# Delhi:Red Fort

a = input('enter city')
if a == 'Mumbai':
    print("Gateway of India")
elif a == 'Delhi':
    print("Red Fort")

enter citydelhi


UNIT - 5

In [65]:
i = 1
n = 500
while i<=n:
   print(i)
   i=i+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


In [66]:
for x in "datascience":
  print(x)
for x in range(5):
  print(x)
for x in range(4,5):
  print(x)
a = [50,60,70,80,90]
for x in a:
  print(x)
for i in range(5):
  if i == 3:
    continue
print("Iam olaf")

d
a
t
a
s
c
i
e
n
c
e
0
1
2
3
4
4
50
60
70
80
90
Iam olaf


UNIT - 6 USER DEFINED FUNCTIONS

In [67]:
def abc():
  print("Hello India")

In [68]:
abc()

Hello India


In [69]:
def details():
  print("The last date of pllaying the bill is this week")
  print("After deadline, you need to pay fine of Rs. 10,000")
  print("Pay bill on time")

In [70]:
for i in range(3):
  a = input("Enter name")
  n = int(input("Enter units of electricity consumed"))
  bill = 10*n
  print("You need to pay Rs",bill)
  details()

Enter nameolaf
Enter units of electricity consumed500
You need to pay Rs 5000
The last date of pllaying the bill is this week
After deadline, you need to pay fine of Rs. 10,000
Pay bill on time
Enter nameolaf
Enter units of electricity consumed500
You need to pay Rs 5000
The last date of pllaying the bill is this week
After deadline, you need to pay fine of Rs. 10,000
Pay bill on time
Enter nameolaf
Enter units of electricity consumed500
You need to pay Rs 5000
The last date of pllaying the bill is this week
After deadline, you need to pay fine of Rs. 10,000
Pay bill on time


In [71]:
def demo(fname):
  print(fname + "Yeti")

In [72]:
demo("Olaf")

OlafYeti


In [73]:
def demo(fname,name):
  print(fname + " " + name + "Yeti")

In [74]:
demo("Elsa", "Anna")

Elsa AnnaYeti


UNIT - 7 STRINGS IN PYTHON

In [75]:
a = "Hello"
print(a)
print(type(a))

Hello
<class 'str'>


In [40]:
a = 'Hello'
print(a)
print(type(a))

Hello
<class 'str'>


In [41]:
b = """Data science is the study of the extrraction of knowledge from data.
 It uses techniques from many fields,including signal processsing,mathematics,
 probability,machine learning, and computer programming,statistics, dataengineering,
 patttern matching, and data visualisation,
  with the goal of extracting usefi]ul knowledge from the data.
  With cocmputer systems able to handle more data, big data is na important aspect of data science."""
print(b)

Data science is the study of the extrraction of knowledge from data.
 It uses techniques from many fields,including signal processsing,mathematics,
 probability,machine learning, and computer programming,statistics, dataengineering,
 patttern matching, and data visualisation,
  with the goal of extracting usefi]ul knowledge from the data.
  With cocmputer systems able to handle more data, big data is na important aspect of data science.


In [42]:
a = "Hello World"
print(a[0])

H


In [43]:
a = "Hello World"
print(a[-2])

l


In [44]:
a = "Hello World"
print(a[-6])

In [45]:
s = "How are you"
print(s[4:7])
print(s[::3])
print(s[::-1])

are
H eo
uoy era woH


In [46]:
a = "Iam Annah and i like Squading"
print(len(a))

29


In [47]:
a = "Candy world is in candy crush"
print("chess" in a)

False


In [48]:
a = "I am so confidence"
print(a.lower())

i am so confidence


In [49]:
a = "I AM SO confidence"
print(a.upper())

I AM SO CONFIDENCE


In [50]:
a = "Hello, World"
print(a.replace('H', 'j'))

jello, World


In [51]:
b = "Python Programming is fabolous"
print(b.replace("fabolous","superb"))

Python Programming is superb


In [52]:
a = 'Hello'
b = 'World'
print(a + b)

HelloWorld


In [53]:
a = "python is great"
b = a.find("g")
print(b)

10


UNIT 8 - LIST
Creating a list

In [54]:
a = ["apple", "banana", "cherry"]
print(a)
print(type(a))

['apple', 'banana', 'cherry']
<class 'list'>


In [55]:
a = ["apple", "banana", "cherry", 2,5.6,-8]
print(a)
print(type(a))

['apple', 'banana', 'cherry', 2, 5.6, -8]
<class 'list'>


Allow Duplicates

In [56]:
a = ["apple", "banana", "cherry", "apple"]
print(a)
print(type(a))

['apple', 'banana', 'cherry', 'apple']
<class 'list'>


###DATA TYPE

In [57]:
a = ["apple", "banana", "cherry", "apple", True, False, 2.5, 5+3j, 5, -9]
print(a)
print(type(a))

['apple', 'banana', 'cherry', 'apple', True, False, 2.5, (5+3j), 5, -9]
<class 'list'>


###LIST LENGTH

In [79]:
a = ["apple", "banana", "cherry", "apple", True, False, 2.5, (5+3j), 5, -9]
print(len(a))

10


###ACCESS ITEM

In [80]:
a = ["apple", "banana", "cherry", "apple", True, False, 2.5, (5+3j), 5, -9]
print(a[3])

apple


In [81]:
b = [5,96,2,3,4,5,5,56]
print(b[-1])

56


###SLICING

In [82]:
c = [10,20,30,40,50,60]
print(c[2:5])

[30, 40, 50]


In [84]:
c = [10,20,30,40,50,60]
print(c[::2])

[10, 30, 50]


In [85]:
c = [10,20,30,40,50,60]
print(c[::3])

[10, 40]


###REVERSE

In [86]:
c = [10,20,30,40,50,60]
print(c[::-1])

[60, 50, 40, 30, 20, 10]


###CHANGE LIST ITEM

In [87]:
a = ["apple", "orange", "guava"]
a[1] = "mango"

In [88]:
print(a)

['apple', 'mango', 'guava']


In [89]:
a = ["apple", "orange", "guava"]
a[1] = 20
print(a)

['apple', 20, 'guava']


###ADD LIST ITEM

##Append

In [90]:
a = ["apple", "orange", "guava"]
a.append("strawberry")
print(a)

['apple', 'orange', 'guava', 'strawberry']


In [91]:
a = ["apple", "orange", "guava"]
a.append("6.32")
print(a)

['apple', 'orange', 'guava', '6.32']


###REMOVE

In [93]:
b = ["apple", "orange", "guava", "strawberry"]
b.remove("orange")
print(b)


['apple', 'guava', 'strawberry']


###JOIN LIST

In [95]:
list1 = [10,20,30]
list2 = [0,1.0,2.0,3.0,0.4]
list3 = ["hello", "students"]

a = list1 + list2 + list3
print(a)

[10, 20, 30, 0, 1.0, 2.0, 3.0, 0.4, 'hello', 'students']


In [97]:
list2 = [0,1.0,2.0,3.0,0.4]
list2.reverse()
print(list2)

[0.4, 3.0, 2.0, 1.0, 0]


###UNIT - TUPLES

In [98]:
a = (1,2,3)
print(a)
print(type(a))

(1, 2, 3)
<class 'tuple'>


###NESTED TUPLE

In [100]:
b = (12,2,4,5.6,"apple",[2,3,5],(10,20,30))
print(b)
print(type(b))

(12, 2, 4, 5.6, 'apple', [2, 3, 5], (10, 20, 30))
<class 'tuple'>


###CREATE A PYTHON TUPLE WITH ONE ELEMENT

In [101]:
var1 = ("hello")
print(var1)
print(type(var1))

hello
<class 'str'>


In [104]:
var1 = ("hello",)
print(var1)
print(type(var1))

('hello',)
<class 'tuple'>


###DUPLICATES

In [105]:
b = (12,2,4,5.6,"apple",[2,3,5],(10,20,30),12,14,15)
print(b)

(12, 2, 4, 5.6, 'apple', [2, 3, 5], (10, 20, 30), 12, 14, 15)


In [107]:
x = ("data", "analyst", "python")
y = list(x)
y[1]="science"
y.append("olaf")
x = tuple(y)
print(x)
print(type(x))

('data', 'science', 'python', 'olaf')
<class 'tuple'>


In [108]:
x = ("data", "analyst", "python")
del x

In [111]:
x = ("data", "analyst", "python")
print(x)

('data', 'analyst', 'python')


###UNIT 10 DICTIONARY

In [112]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993
}

print(a)
print(type(a))

{'ID': 121, 'color': 'black', 'year': 1993}
<class 'dict'>


###ORDERED

In [113]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993
}

print(a)
print(a['color'])

{'ID': 121, 'color': 'black', 'year': 1993}
black


###DUPLICATES NOT ALLOWED

In [115]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}

print(a)

{'ID': 121, 'color': 'black', 'year': 2000}


###LENGTH

In [117]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}

print(len(a))

3


###DICT CONSTRUCTOR

In [118]:
a = dict(name ="pookie", age = 20, country = "Newzealand")
print(a)

{'name': 'pookie', 'age': 20, 'country': 'Newzealand'}


###CHANGE

In [121]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}
a["color"] = 'red'
print(a)

{'ID': 121, 'color': 'red', 'year': 2000}


###ADD

In [123]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}
a.update({"mail id" : "olaf@gmail.com"})
print(a)

{'ID': 121, 'color': 'black', 'year': 2000, 'mail id': 'olaf@gmail.com'}


###REMOVE

In [124]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}
a.pop("year")
print(a)

{'ID': 121, 'color': 'black'}


###CLEAR

In [125]:
a = {
    "ID" : 121,
    'color':"black",
    "year":1993,
    "year" :2000
}
a.clear()
print(a)

{}


###UNIT 11 SETS


CREATING

In [131]:
a = {"animals", "ball", "candy",}
print(a)
print(type(a))

{'ball', 'candy', 'animals'}
<class 'set'>


###DUPLICATES NOT ALLOWED

In [132]:
a = {"animals", "ball", "candy", 3,4,56,7,8,8,8,}
print(a)
print(type(a))

{'ball', 3, 4, 7, 8, 'animals', 'candy', 56}
<class 'set'>


In [133]:
a = {"animals", "ball", "candy", 3,4,56,7,8,8,8, True, 1}
print(a)
print(type(a))

{'ball', True, 3, 4, 7, 8, 'animals', 'candy', 56}
<class 'set'>


###SET CONSTRUCTOR

In [134]:
a = set((1,3,5,7))
print(a)
print(type(a))

{1, 3, 5, 7}
<class 'set'>


###EMPTY SET

In [136]:
a = {}
print(a)
print(type(a))


{}
<class 'dict'>


In [137]:
b = set()
print(b)
print(type(b))

set()
<class 'set'>


In [138]:
a = {"animals", "ball", "candy", 3,4,56,7,8,8,8,}
print("candy" in a)

True


In [139]:
a = {"animals", "ball", "candy", 3,4,56,7,8,8,8,}
print("code" in a)

False


###REMOVE

In [140]:
a = {"animals", "ball", "candy", 3,4,56,7,8,8,8,}
a.remove("ball")
print(a)

{3, 4, 7, 8, 'animals', 'candy', 56}


###CLEAR

In [141]:
a =  {"animals", "ball", "candy", 3,4,56,7,8,8,8,}
a.clear()
print(a)

set()


###JOIN 2 SETS

In [142]:
a = {10,20,30,}
b = {0.1,0.2,0.3}
x = a.union(b)
print(x)

{0.1, 0.2, 0.3, 20, 10, 30}


###UNIT 12 NUMPY

In [144]:
import time
import numpy as np

#Create large data
size = 1000000

#Python list
list1 = list(range(size))
list2 = list(range(size))

#Numpy Array
arr1 = np.array(list1)
arr2 = np.array(list2)

#list addition timing
start = time.time()

result_list = []
for i in range(size):
  result_list.append(list1[i] + list2[i])

end = time.time()

print("List Time:", end - start)


#Numpy adddition time

start = time.time()

result_array = arr1 +arr2
end = time.time()

print("Numpy Time:", end - start)

List Time: 0.20838522911071777
Numpy Time: 0.0045948028564453125


In [145]:
import numpy as np

In [146]:
print(np.__version__)

2.1.3


###ARRAY

In [148]:
a = [1,2,3,4]

b = np.array([1,2,3,4])

print(a)
print(b)

[1, 2, 3, 4]
[1 2 3 4]


In [150]:
c = np.zeros(3)
print(c)

[0. 0. 0.]


In [151]:
d = np.ones(4)
print(d)

[1. 1. 1. 1.]


In [153]:
e = np.arange(0,10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


###MUTI DIMENSIONAL ARRAY

In [154]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr)

[[1 2 3]
 [3 4 5]]


###5 D

In [155]:
arr = np.array([1,2,3,4],ndmin = 5)
print(arr)

[[[[[1 2 3 4]]]]]


###CHECK

In [156]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6,]])
d = np.array([[[1,2,3],[4,5,6,]],[[1,2,3],[4,5,6]]])


print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


###SHAPE & SIZE

In [158]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr)

[[1 2 3]
 [3 4 5]]


In [159]:
arr.shape
arr.size

6

###INDEXING & SLICING

In [165]:
arr = np.array([10,20,30,40])
print(arr[1])
print(arr)

20
[10 20 30 40]


###MATHEMATICAL OPERATIONS

In [162]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


In [163]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a*b)

[ 4 10 18]


###AGGREGATION FUNCTION

In [164]:
arr = np.array([1,2,3,4])
print(np.sum(arr))

10


###RESHAPE

In [166]:
arr = np.array([1,2,3,4,5,6])
new_arr = arr.reshape(2,3)

In [167]:
print(new_arr)

[[1 2 3]
 [4 5 6]]


###RANDOM NUMBERS

In [168]:
np.random.rand(3)

array([0.51396573, 0.12029498, 0.354552  ])

In [169]:
np.random.rand(10)

array([0.02157873, 0.06266581, 0.88319253, 0.91346691, 0.01492463,
       0.05348004, 0.08881356, 0.72249496, 0.84991453, 0.2172545 ])

In [170]:
np.random.randint(1,10,5)

array([9, 2, 2, 3, 7])