<a href="https://colab.research.google.com/github/samreenkauser/Rebounce-Applied-AI-and-Analytics-Codes/blob/main/S5_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 1 - Create a Numpy array**

In [ ]:
import numpy as np

rainfall = np.array([820,1340,640,2100,1560,990])
print(rainfall)
print(type(rainfall))
print(rainfall.shape)
print(rainfall.size)

[ 820 1340  640 2100 1560  990]
<class 'numpy.ndarray'>
(6,)
6


**Exercise 2 - Census years with arange**

In [ ]:
import numpy as np

np.arange(1951,2011,10)

start = 1951
stop = 2012
step = 10
years = np.arange(start,stop,step)
print(years)


[1951 1961 1971 1981 1991 2001 2011]


**Exercise 3 - A Blank allocation grid**

In [ ]:
import numpy as np

np.zeros((4,3))
allocation_grid = np.zeros((4,3))
print(allocation_grid)
print(allocation_grid.shape)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


**Exercise 4 - Total Agriculture Production**

In [ ]:
import numpy as np

rabi = np.array([12,18,9,22,15])
kharif = np.array([8,11,14,9,10])

print(rabi + kharif)
print(rabi - kharif)
print(rabi * kharif)
print(rabi / kharif)


[20 29 23 31 25]
[ 4  7 -5 13  5]
[ 96 198 126 198 150]
[1.5        1.63636364 0.64285714 2.44444444 1.5       ]


**Exercise 5 - Pick Out One District (indexing)**

In [ ]:
import numpy as np

literacy = np.array([87,77,70,95,76,82,91])

print(literacy[0]) # First element
print(literacy[-1]) # Last element
print(literacy[3]) # Fourth element

87
91
95


**Exercise 6 - Slice a forest-cover grid**

In [ ]:
import numpy as np

forest_grid = np.array([
    [24,25,27],
    [46,47,47],
    [7,8,9]
])
forest_cover = forest_grid[0,0] # Corrected variable name and used integer indexing as an example
print(forest_grid)
print(forest_cover)

[[24 25 27]
 [46 47 47]
 [ 7  8  9]]
24


E**xercise  7 - Revise a Budget Figure(updating)**

In [ ]:
import numpy as np

budget_core = np.array([180,240,300,360,420])

print(budget_core[1])
budget_core[-2:] = 250

240


**Exercise 8 - Budget increase with broadcasting**

In [ ]:
import numpy as np

budget_crore = np.array([180,240,300,360,420])

print(budget_crore * 1.08)
print(budget_crore + 10)

[194.4 259.2 324.  388.8 453.6]
[190 250 310 370 430]


**Exercise 9 - Rainfall statistics (Aggregation)**

In [ ]:
import numpy as np

rainfall = np.array([820,1340,640,2100,1560,990,1180,760])

print(rainfall.sum())
print(round(rainfall.mean(),1))
print(rainfall.max())
print(rainfall.min())
print(round(rainfall.std(),1))

9390
1173.8
2100
640
454.1


**Exercise 10 = Filter states by literacy (Boolean Masking)**

In [ ]:
import numpy as np
import pandas as pd

state_data = pd.read_csv("state_indicators.csv")

# Correcting the comparison for 'literacy_rate'
# This creates a boolean Series (mask) where True means literacy_rate >= 85
literacy_rate_mask = state_data['literacy_rate'] >= 85
print(literacy_rate_mask)is True
rates = state_data["literacy_rate"].to_numpy()
print(rates[literacy_rate_mask])
# Correcting the second print statement to count how many states meet the criteria
# .sum() on a boolean Series counts the number of True values
print(literacy_rate_mask.sum())

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11     True
Name: literacy_rate, dtype: bool
[96 85 88 87]
4


**Exercise 11 - Simulate solar output(random with a seed)**

In [ ]:
import numpy as np

np.random.seed(42)

sample_plant = np.random.randint(100,500, size = 6)

print(sample_plant)
print(sample_plant.mean())

[202 448 370 206 171 288]
280.8333333333333


**Exercise 12 - Mini Challenge : renewable energy report**

In [ ]:
import numpy as np
import pandas as pd

state_data = pd.read_csv("state_indicators.csv")
states = state_data["state"].to_numpy()
renewable = state_data["renewable_mw"].to_numpy()

print(renewable.mean())
print(np.argmax(renewable))
print(renewable[renewable > 5000])

4645.833333333333
10
[10500 12800  8600 15400]
